### ISSUE TITLE
[PACE-27] Keep generated docs up-to-date

### ISSUE THREAD

**Issue by bvdeenen** [getstrm/cli#11]
`make docs` generates `generated_docs/*.md`, but these don't magically appear in the pace repo's `docs/cli-docs` directory.
Steps to be done on release:
* `make docs`
* copy docs into pace repo `docs/cli-docs`
* update `docs/SUMMARY.md` in the pace repo
* commit pace repo and push

<sub>[PACE-27](https://linear.app/strmprivacy/issue/PACE-27/keep-generated-docs-up-to-date)</sub>

**Comment by trietsch** [comment]
@bob this one

**Comment by bobvandenhoogen** [comment]
Merged in #12
